###
POST http://localhost:9000/plantsApi/users HTTP/1.1
Content-Type: application/json

{
    "name": "Larisa Fernandez",
    "email":"lariferz565@gmail.com",
    "password":"trestristestigres",
    "age": 33,
    "position": "Normal user"
}